-- Estância 3 Amores
-- Schema inicial do banco de dados
-- Tabelas principais utilizadas pelo sistema.

-- =========================================================
-- CLIENTES
-- =========================================================

create table public.clientes (
  id bigint generated by default as identity primary key,
  nome text not null,
  telefone text not null,
  endereco text not null,
  created_at timestamptz not null default now(),

  constraint clientes_nome_minimo
    check (char_length(trim(nome)) >= 3)
);


-- =========================================================
-- PRODUTOS
-- =========================================================

create table public.produtos (
  id bigint generated by default as identity primary key,
  nome text not null,
  unidade text not null,
  preco numeric(10, 2) not null,
  categoria text not null,
  status text not null default 'pronta-entrega',
  estoque integer not null,
  imagem text not null,
  created_at timestamptz not null default now(),

  constraint produtos_preco_valido
    check (preco >= 0),

  constraint produtos_estoque_valido
    check (estoque >= 0),

  constraint produtos_categoria_valida
    check (
      categoria in (
        'Legumes',
        'Verduras',
        'Frutas',
        'Grãos'
      )
    ),

  constraint produtos_status_valido
    check (
      status in (
        'pronta-entrega',
        'em-crescimento'
      )
    )
);


-- =========================================================
-- PLANTIOS
-- =========================================================

create table public.plantios (
  id bigint generated by default as identity primary key,
  nome text not null,
  tipo text not null,
  area numeric(10, 2) not null,
  quantidade integer not null,
  created_at timestamptz not null default now(),

  constraint plantios_area_valida
    check (area > 0),

  constraint plantios_quantidade_valida
    check (quantidade > 0)
);


-- =========================================================
-- PEDIDOS
-- =========================================================

create table public.pedidos (
  id bigint generated by default as identity primary key,
  cliente_id bigint not null,
  telefone text not null,
  status text not null default 'Pendente',
  data date not null,
  created_at timestamptz not null default now(),

  constraint pedidos_cliente_fk
    foreign key (cliente_id)
    references public.clientes(id)
    on delete restrict,

  constraint pedidos_status_valido
    check (
      status in (
        'Pendente',
        'Em Rota',
        'Entregue'
      )
    )
);


-- =========================================================
-- PEDIDO_ITENS
-- =========================================================

create table public.pedido_itens (
  id bigint generated by default as identity primary key,
  pedido_id bigint not null,
  produto_id bigint not null,
  quantidade integer not null,
  preco_unitario numeric(10, 2) not null,
  created_at timestamptz not null default now(),

  constraint pedido_itens_pedido_fk
    foreign key (pedido_id)
    references public.pedidos(id)
    on delete cascade,

  constraint pedido_itens_produto_fk
    foreign key (produto_id)
    references public.produtos(id)
    on delete restrict,

  constraint pedido_itens_quantidade_valida
    check (quantidade > 0),

  constraint pedido_itens_preco_valido
    check (preco_unitario >= 0)
);


-- =========================================================
-- ENTREGAS
-- =========================================================

create table public.entregas (
  id bigint generated by default as identity primary key,
  cliente_id bigint not null,
  data date not null,
  endereco text not null,
  status text not null default 'Pendente',
  created_at timestamptz not null default now(),

  constraint entregas_cliente_fk
    foreign key (cliente_id)
    references public.clientes(id)
    on delete restrict,

  constraint entregas_status_valido
    check (
      status in (
        'Pendente',
        'Em Rota',
        'Cancelado',
        'Entregue'
      )
    )
);


-- =========================================================
-- ÍNDICES DOS RELACIONAMENTOS
-- =========================================================

create index idx_pedidos_cliente_id
  on public.pedidos(cliente_id);

create index idx_pedido_itens_pedido_id
  on public.pedido_itens(pedido_id);

create index idx_pedido_itens_produto_id
  on public.pedido_itens(produto_id);

create index idx_entregas_cliente_id
  on public.entregas(cliente_id);


-- =========================================================
-- ROW LEVEL SECURITY
-- =========================================================
-- As políticas de acesso serão configuradas separadamente,
-- em conjunto com a autenticação real do sistema.

alter table public.clientes enable row level security;
alter table public.produtos enable row level security;
alter table public.plantios enable row level security;
alter table public.pedidos enable row level security;
alter table public.pedido_itens enable row level security;
alter table public.entregas enable row level security;